(function(){function e(a){var b=1,c,d;if(a)for(b=0,d=a.length-1;0<=d;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=0!=c?b^c>>21:b;return b};function f(){var a=window._gaUserPrefs;return a&&a.ioo&&a.ioo()}function g(a,b){return"string"==typeof window[a]?window[a]:b}function h(){var a=g("_udn","auto");return"auto"==a?(a=document.domain,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)),a):a&&""!=a&&"none"!=a?a:null}function k(){var a=h(),b=g("_uhash","on");if(null==a||"off"==b)return 1;a=a.toLowerCase();return e(a)}
function l(a,b,c){var d=h(),m=g("_utcp","/");if(!f()){b=k()+"."+b;null!=d&&(b+=";domain="+d);b+=";path="+m;if("string"==typeof window._utimeout&&""!=window._utimeout)try{c=parseInt(window._utimeout,10)}catch(n){}0<c&&(b+=";expires="+(new Date((new Date).getTime()+1E3*c)).toGMTString());document.cookie=a+"="+b}}l('__utmx','b4WAd2xRR0ybC6ydhoAj9w$21082672-11:',46656000);l('__utmxx','b4WAd2xRR0ybC6ydhoAj9w$21082672-11:1469568641:15552000',46656000);})();
function q(a){var b=1,d,c;if(a)for(b=0,c=a.length-1;0<=c;c--)d=a.charCodeAt(c),b=(b<<6&268435455)+d+(d<<14),d=b&266338304,b=0!=d?b^d>>21:b;return b};var utmx_url_utils={maxUrlLength:2048,queryStringToArray:function(a,b){for(var d=a.split(b),c=[],e=0;e<d.length;e++)if(0!=d[e].length){var f=d[e].split("="),g=f[0],f=2<=f.length?f[1]:null;c.push([g,f])}return c},arrayToQueryString:function(a,b){for(var d=[],c=0;c<a.length;c++){0!=c&&d.push(b);d.push(a[c][0]);var e=a[c][1];null!=e&&(d.push("="),d.push(e))}return d.join("")},trimUrl:function(a){if(0<=a.indexOf("http://"))return a.replace("http://","");if(0<=a.indexOf("https://"))return a.replace("https://",
"");var b=a.indexOf("#");if(0<b)return a.substring(0,b);b=a.indexOf("?");if(0<b)return a.substring(0,b);b=a.indexOf("/");return 0<b?a.substring(0,b):""},removeOverflowingParam:function(a,b,d,c){if(a.length<=b)return a;var e=a.split("?");if(2>e.length)return a;for(var f=e[1].split("#"),g=utmx_url_utils.queryStringToArray(f[0],"&"),h=0;h<g.length;++h)if(g[h][0]==d){if(!c||2>g[h].length){g.splice(h,1);break}for(c=d=g[h][1];a.length-d.length+c.length>b&&""!=c;)c=encodeURIComponent(utmx_url_utils.trimUrl(decodeURIComponent(c)));
""==c?g.splice(h,1):g[h][1]=c;break}f[0]=utmx_url_utils.arrayToQueryString(g,"&");e[1]=f.join("#");return e.join(0<f[0].length?"?":"")},removeOurParamsFromReferrer:function(a){a=utmx_url_utils.removeOverflowingParam(a,0,"utm_expid",!1);return a=utmx_url_utils.removeOverflowingParam(a,0,"utm_referrer",!1)},trimUrlEnd:function(a,b){for(var d in b)a.charAt(a.length-1)==b[d]&&(a=a.substring(0,a.length-1));return a},resolveRelativeUrl:function(a,b){var d=/^([\w]+):\/\/([^/?]+)\/?(.*)$/,c=/^([^?#]*\/)*([^/?#]*)([^#]*)(.*)$/;
if(d.test(b))return b;var e=d.exec(a),f=e[1],d=f+"://"+e[2]+"/",g=c.exec(e[3]),h=g[1]||"",k=g[2]||"",g=g[3]||"";if("//"==b.substring(0,2))return f+":"+b;var n="",e=f="";"/"==b.charAt(0)?(c=b.substr(1),h=""):(e=c.exec(b),c=e[1]||"",n=e[2]||"",f=e[3]||"",e=e[4]||"");if(c||n){c=h+c+n;c=c.replace(/^(\.\/)+(\.$)?|\/\.(?=\/)|(^|\/)\.$/g,"$3");for(h=15;/(^|\/)\.\.(\/|$)/.test(c)&&0<--h;)c=c.replace(/(^|[^\/]*\/)\.\.(\/|$)/g,"");c+=f+e}else if(f)c=h+k+f+e;else if(e)c=h+k+g+e;else return a;return d+c}};
function utmx_section(a){return utmx("section",a)}
function utmx(a,b,d,c){function e(b,a,c){function e(a,b,c,d,f,g,p){function h(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]);for(d=0;d<b.length;d++){for(var e=b[d][0],f=!1,g=0;g<a.length;g++)if(e==a[g][0]){f=!0;break}f||c.push(b[d])}return c}function l(a,b){for(var c=b.length-1;0<=c;c--)b[c][0]==a&&b.splice(c,1);return b}var k=new String(b),m=k.indexOf(d);if(0<=m||p){b="";0<=m&&(b=g?k.indexOf(g,m):-1,0>b&&(b=k.length),b=k.substring(m+1,b));m=c.indexOf(d);0>m&&(m=0);var n=g?c.indexOf(g,m):-1;0>
n&&(n=c.length);k=c.substring(0,m?m:n);g=c.substring(n);a?f=b:(a=0==m?"":c.substring(m+1,n),a=utmx_url_utils.queryStringToArray(a,f),p&&(a=l(p[0],a),a.push(p)),p=h(a,utmx_url_utils.queryStringToArray(b,f)),f=utmx_url_utils.arrayToQueryString(p,f));f&&0<f.length&&(k+=d+f);c=k+=g}return c}if(!utmx("live")&&!utmx("preview"))return!0;a||(a="0");b=k(b);if(!b)return!0;var d='21082672-11.b4WAd2xRR0ybC6ydhoAj9w.0',f=document.referrer,
f=utmx_url_utils.removeOurParamsFromReferrer(f),g=b.index;if(a==g)a=e(!1,"",document.location.href,"?","&","#",["utm_expid",d]),f&&(a=e(!1,document.location.href,a,"?","&","#",["utm_referrer",encodeURIComponent(f)]));else{for(a=utmx_url_utils.resolveRelativeUrl(document.location.href,b.contents);;){g=a.length;if(0>=g||" "!=a.charAt(g-1))break;a=a.substring(0,g-1)}a=e(!1,document.location,a,"?","&","#",["utm_expid",d]);f&&(a=e(!1,document.location,a,"?","&","#",["utm_referrer",
encodeURIComponent(f)]));a=e(!0,document.location,a,"#",";");for(d=0;" "==a.charAt(d);)d++;0<d&&(a=a.substring(d));"http://"!=a.substring(0,7).toLowerCase()&&"https://"!=a.substring(0,8).toLowerCase()&&(a="http://"+a);c&&(b.contents=a,b=[b],a=c(b))}a=utmx_url_utils.removeOverflowingParam(a,utmx_url_utils.maxUrlLength,"utm_referrer",!0);a=utmx_url_utils.removeOverflowingParam(a,utmx_url_utils.maxUrlLength,"utm_expid",!1);(a=utmx_url_utils.trimUrlEnd(a,["#","&","?"]))&&document.location.replace(a);
return!0}function f(a){(a=k(a))&&0<a.index&&document.write(a.contents+"<nosc"+"ript>");return!0}function g(){if(null!=utmx_global_vd)return undefined}function h(){if(null!=utmx_global_vd)return undefined}function k(a){if(null!=utmx_global_vd)return utmx_global_vd[a]}function n(a){if((a=k(a))&&0<a.index)return a.contents}function r(a){if((a=k(a))&&0<=a.index)return a.index}function t(a){"string"==typeof a&&(a=a.toLowerCase());return q(a)}function u(){return false&&
null!=utmx_global_vd}function v(){return false}var l;switch(a){case "section":l=f(""+b);break;case "url":l=e(b,d,c);break;case "variation":l=k(""+b);break;case "variation_content":l=n(""+b);break;case "variation_number":l=r(""+b);break;case "combination":l=g();break;case "combination_string":l=h();break;case "domain_hash":l=t(""+b);break;case "live":l=u();break;case "preview":l=v()}return l}var utmx_global_vd = null;
(function(){function a(){var a=window._gaUserPrefs;return a&&a.ioo&&a.ioo()}if("undefined"!=typeof navigator.cookieEnabled&&!navigator.cookieEnabled)return!1;if(utmx("preview"))return!0;if(a())return!1;var b=utmx("domain_hash",document.location),d=document.cookie,b="__utmx_k_"+b,c=d.indexOf(b+"="),e=0;0<=c&&(e=d.indexOf(";",c),0>=e&&(e=d.length),e=parseInt(d.substring(c+b.length+1,e),10));d=new Date;c=d.getTime();d.setTime(c+2E3);e+=1;document.cookie=b+"="+e+";expires="+d.toGMTString();
return 10<e||0>document.cookie.indexOf(b+"="+e)?!1:!0})()&&(utmx_global_vd={'A/B':{index:0,contents:'https://theepochtimes.com'}});
