//<script>
bouncex.state = {"newvid":true,"iol":true,"tn":1469568502,"pvid":1,"rc":false,"mobile":false,"vip":"65.204.229.11"};
bouncex.cookie = {"sid":1,"fvt":1469568502,"vid":1469568502066559,"ao":0,"as":0,"vpv":1,"d":"d","lp":"http%3A%2F%2Fwww.theepochtimes.com%2Fn3%2F1952884-how-dress-for-success-ceo-joi-gordon-gives-women-hope%2F","r":"www.google.com","cvt":1469568502,"gcr":27,"m":0,"did":"3104522784299037108","lvt":1469568502,"campaigns":{"318265":{"vv":0,"lvt":1469568502}}};
bouncex.brandStyles = false;
bouncex.webfonts = false;
bouncex.campaigns = {"318265":{"ad_shown":false,"pid":"318264","ctype":"other","activations":[{"activation":"back","prop":"landing_page"},{"activation":"bounce","prop":"","val":""},{"activation":"inactivity","val":"60"}],"overlay":"none","coverlay":"none","ctop":"none","cbottom":"none","bottom":"none","callout":"none","callout_t":"","callout_pt":null,"callout_pos":"lb","header_bottom_alignment":"center","callout_anchor_pos":"lm","blur_gate_enabled":0,"blur_gate_inclusions":"","blur_gate_exclusions":"","dom_placement_method":"","callout_voffset":"0","callout_hoffset":"0","acas":0,"top":"none","overlay_teleport_html":"","overlay_teleport_type":"_blank","opacity":0.9,"color":"#000000","close_button_delay":0,"custom_tab_title":[],"show_close":1,"show_close_step":0,"close_redirect_url":null,"close_redirect_type":"_self","activation_delay":0,"closed_no_show":0,"ipc":0,"mas":1,"mao":0,"map":1,"iao":"0","rao":"0","tvao":"0","is_ec":false,"is_api":false,"is_man":0,"ad_auto_close":0,"activation_offset":0,"header_top_nano":0,"header_bottom_nano":0,"type":"none","ttype":"control","hbna":"anypage","hbnbg":"0","htna":"none","htnbg":"1","ad_visible":false,"osfn":null,"tes":"1","te":"no_effect","te2":"no_effect","t_valign":"top","b_valign":"bottom","qbxtest":false,"submission_redirect":null,"submission_redirect_delay":2,"osfn_website":"","supress_overlay":0,"repress_overlay":0,"supress_top":0,"repress_top":0,"supress_bottom":0,"repress_bottom":0,"ng":1,"images":[],"edw":0,"event_js":"","ga_i":{"impression":0,"click":0,"submission":0,"label":"Insight - Ads - Insight Campaign | Desktop | Total Available Impressions (318264): None - control - Insight Campaign | Desktop | Total Available Impressions (318265)"},"noCreative":true,"gbi":false,"html":"","control":true}};
bouncex.gbi.stacks = false;
bouncex.debug = false;

bouncex.init();
